### ISSUE TITLE
 Small separator icon

### ISSUE THREAD

**Issue by fvmsantos** [caiocutrim/cp-oh-my-zsh-theme#1]
In my terminal the icon separator was small.
What can it be?

I'm using pantheon terminal. (Elementary OS Freya, based on Ubuntu 14)

![screenshot from 2016-05-05 17 37 47](https://cloud.githubusercontent.com/assets/6462673/15056467/1dad2488-12e8-11e6-89ef-d3419eccd8ae.png)

**Comment by caiocutrim** [comment]
I recommend you to use Dejavu Sans Mono for powerline terminal font, it's easy to set up, sorry for delay
